# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sp7TTQQUUB4B43AjXztPBSxZcrY1n6dY
"""



"""PAKISTAN POPULATION ANALYSIS

TABLE OF CONTENTS
1. IMPORTING LIBRARIES

2. LOADING DATA

3. Exploratory Data Analysis

4. DATA CLEANING

5. HYPOTHESIS BUIDLING

6. RULAR POPULATION ANALYSIS

7. URBAN POPULATION ANALYSIS

8. FINDINGS

9. FINDINGS

PURPOSE
Which Area Or Provice has the highest Area per square?

What is the highest Area Occupied by a province(Province Name)?

How much population for Rular Area is increased from 1998 to 2017 ?

The population Of Rular in percentage?

How much population for Urban Area is increased from 1998 to 2017 ?

The population Of Urban in percentage?
"""

#importing Neccessory Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import colors

import warnings
import sys
if not sys.warnoptions:
    warnings.simplefilter("ignore")
np.random.seed(42)

"""LOADING DATA SET"""

df = pd.read_csv('/content/sub-division_population_of_pakistan[1].csv')



"""The dataset collected from the Source has the following Description:
Description
This dataset contains demographic information from the Pakistan Population Census conducted in 2017. It provides detailed population data at various administrative levels within Pakistan, including provinces, divisions, districts, and sub-divisions. The dataset also includes information on urban and rural populations, gender distribution, transgender individuals, sex ratios, population figures from the 1998 census, and annual growth rates.

Features
Province: The administrative provinces or regions of Pakistan where the census data was collected.

Division: The divisions within each province. Divisions are the second level of administrative divisions in Pakistan.

District: Districts within each division, representing larger administrative units.

Sub-Division: Sub-divisions or tehsils within each district, providing more localized data.

Area: The land area (in square kilometers) of each sub-division.

Urban Population 2017: The population of urban areas within each sub-division for the year 2017.

Rural Population 2017: The population of rural areas within each sub-division for the year 2017.

Male Population 2017: The male population within each sub-division for the year 2017.

Female Population 2017: The female population within each sub-division for the year 2017.

Transgender Population 2017: The population of transgender individuals within each sub-division for the year 2017.

Sex Ratio 2017: The sex ratio, calculated as the number of females per 1000 males, within each sub-division for the year 2017.

Population in 1998: The total population of each sub-division as recorded in the 1998 census.

Annual Growth Rate: The annual growth rate of the population in each sub-division, calculated as the percentage increase from 1998 to 2017.

Data Source
The data in this dataset was collected from official Pakistan Population Census reports and may include data from various government sources. It is essential to provide proper attribution and reference the original sources when using this dataset for analysis or research.

Data Usage
Researchers and analysts can use this dataset to explore demographic trends, population growth, urbanization rates, gender distribution, and more within Pakistan at different administrative levels. Ensure compliance with ethical and legal guidelines when using this data for research or public sharing.

Please note that this description is a template, and you should adapt it based on the actual data sources and specific details of your dataset when creating it for Kaggle or any other platform.
"""

df.info()

# Defining the styling map
def styles(row):
    # Defining alternate colors pattern
    row_colors = ['#41C9E2', '#FF8E8F']
    text_colors = ['#124076', '#5D0E41']

    # Targetting the index of the current row
    index = df[df.apply(lambda x: (x == row).all(), axis=1)].index[0]

    # Determining the background color and text color based on the index
    background_color = row_colors[index % len(row_colors)]
    text_color = text_colors[index % len(text_colors)]

    # Applying styles to the row cells
    style = [f'background-color: {background_color}; color: {text_color}; border: 1px double black;'] * len(row)
    return style

# Applying the styles to the DataFrame
styled_df = df.head(8).style.apply(styles, axis=1).set_table_styles([
    {"selector": "th", "props": [("color", 'white'), ("background-color", "#A0153E"), ("border", '1px solid black')]}
])

styled_df

# max column printing option
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

#printing Again the dataset
df.head()

df.columns

# lets have a look on data types
df.dtypes

df.describe()

df.describe().transpose()
# or
# df.describe().T

# How many are the missing values
df.isnull().sum()

df.columns

#To plot some selected features
#Setting up colors prefrences
sns.set(rc={"axes.facecolor":"#FFF9ED","figure.facecolor":"#FFF9ED"})
pallet = ["#682F2F", "#9E726F", "#D6B2B1", "#B9C0C9", "#9F8A78", "#F3AB60"]
cmap = colors.ListedColormap(["#682F2F", "#9E726F", "#D6B2B1", "#B9C0C9", "#9F8A78", "#F3AB60"])
#Plotting following features
To_Plot = ["AREA (sq.km)"]

plt.figure()
plt.figure(figsize=(5, 5))
sns.boxplot(df[To_Plot],palette= (["#682F2F","#F3AB60"]))

#Taking hue
plt.show()

# Using boxplot
# sns.boxplot(df, x='AREA (sq.km)')

# we can change the axis to y axis
plt.figure(figsize=(5, 5))
sns.boxplot(df, x='AREA (sq.km)')

sns.set(rc={"axes.facecolor":"#FFF9ED","figure.facecolor":"#FFF9ED"})
pallet = ["#682F2F", "#9E726F", "#D6B2B1", "#B9C0C9", "#9F8A78", "#F3AB60"]
cmap = colors.ListedColormap(["#682F2F", "#9E726F", "#D6B2B1", "#B9C0C9", "#9F8A78", "#F3AB60"])

plt.figure()
plt.figure(figsize=(15, 8))
sns.boxplot(df, y='AREA (sq.km)' , x='PROVINCE',hue='PROVINCE',palette= (["#682F2F","#F3AB60"]))

#Taking hue
plt.show()

print(df['AREA (sq.km)'].max())
# now storing this in a variable for further analysis
maximumArea = df['AREA (sq.km)'].max()

print("Maximum area is: ", maximumArea)

max_Province= df[['PROVINCE','DIVISION','DISTRICT','SUB DIVISION','AREA (sq.km)']].max()
print(max_Province)

print('Which District has the maximum Area ?')
print('The District which has maximum Area is PUNJAB')

print('----------------------------------------------------')
print('Which Province has the maximum Area ?')
print('The Province that has the maximum Area is: SINDH')

print('----------------------------------------------------')
print('What are the maximum Area ?')
print('The maximum Area is: ', maximumArea)

df.columns

df.describe().T

df.groupby('PROVINCE')['ALL SEXES (RURAL)'].mean()

df.groupby(['PROVINCE','DIVISION', 'DISTRICT'])['ALL SEXES (RURAL)'].mean().sort_values(ascending=False).head(10)

# Looking it province level
df.groupby('PROVINCE')['POPULATION 1998 (RURAL)']

df['POPULATION 1998 (RURAL)'].sum()

df['ALL SEXES (RURAL)'].sum()

pop_rular_1998 = df['POPULATION 1998 (RURAL)'].sum()
pop_rular_2017 = df['ALL SEXES (RURAL)'].sum()

pop_increased = pop_rular_2017 - pop_rular_1998

print('The RULAR population from 1998 to 2017 is increased by: ', pop_increased)

Rular_percentage = pop_rular_1998/pop_rular_2017 * 100


print('The Rular Population From 1998 to 2017 in percentage is increased by: ', Rular_percentage)
# print(f{"RULAR population from 1998 to 2017 is increased by", {pop_increased}, "and in percentage",{Rular_percentage}})

pop_Urban_1998 = df['POPULATION 1998 (URBAN)'].sum()
pop_Urban_2017 = df['ALL SEXES (URBAN)'].sum()

pop_increased = pop_Urban_2017 - pop_Urban_1998

print('The Urban population from 1998 to 2017 is increased by: ', pop_increased)

Urban_percentage = pop_Urban_1998/pop_Urban_2017 * 100



print('The Urban Population From 1998 to 2017 in percentage is increased by: ', Urban_percentage)
# print(f{"RULAR population from 1998 to 2017 is increased by", {pop_increased}, "and in percentage",{Rular_percentage}})



"""FINDINGS
Place with the Maximum Area: Punjab has the maximum area according to the box plot.
Province with the Maximum Area: Sindh Province in the Sindh district has the maximum area.
Maximum Area Value: The maximum area is 18,374 square kilometers.
Percentage Increase in Rural Population (1998-2017): The rural population increased by 67.98%.
Percentage Increase in Urban Population (1998-2017): The urban population increased by 56.89%.
"""

